version: "3"

# Modified from https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
    pihole:
        container_name: "pihole"
        image: pihole/pihole:${VERSION}
        environment:
            ServerIP: ${LOCAL_IP}
            VIRTUAL_HOST: ${VIRTUAL_HOST}
        env_file:
            - "./.env"
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            # - "80:80/tcp"
            # - "443:443/tcp"
        volumes:
            - "./etc-pihole/:/etc/pihole/"
            - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
        dns:
            - "127.0.0.1"
            - "1.1.1.1"
        extra_hosts:
            - "${VIRTUAL_HOST}:${LOCAL_IP}"
        networks:
            - "traefik"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pihole.rule=HostRegexp(`${VIRTUAL_HOST}`, `{catchall:.*}`)"
            - "traefik.http.routers.pihole.priority=1"
            - "traefik.http.services.pihole.loadbalancer.server.port=80"
        cap_add:
            - "NET_ADMIN"
        restart: "unless-stopped"

networks:
    traefik:
        external: true
