version: "3"

services:
    traefik:
        image: traefik:${VERSION}
        ports:
            - "80:80"
            - "443:443"
            # Admin
            # - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - ./certs:/etc/certs:ro
            - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
            - ./config/static.yml:/etc/traefik/traefik.yml:ro
        networks:
            - "traefik"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.tls=true"
            - "traefik.http.routers.traefik.rule=Host(`traefik.home.local`)"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        restart: "unless-stopped"

networks:
    traefik:
        external: true
