global:
    sendAnonymousUsage: false

api:
    dashboard: true
    insecure: true

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        watch: true
        exposedByDefault: false
        network: traefik

    file:
        filename: /etc/traefik/dynamic.yml
        watch: true

log:
    level: INFO

entryPoints:
    http:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: https
                    scheme: https
    https:
        address: ":443"
